server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # ✅ PUBLIC — no AuthFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**

        # 🔒 PROTECTED — AuthFilter applied
        - id: workspace-service
          uri: lb://workspace-service
          predicates:
            - Path=/api/v1/workspaces/**
          filters:
            - AuthFilter

        - id: project-task-service
          uri: lb://project-task-service
          predicates:
            - Path=/api/v1/projects/**,/api/v1/tasks/**
          filters:
            - AuthFilter

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - AuthFilter

        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/v1/files/**
          filters:
            - AuthFilter

jwt:
  secret: bXlzdXBlcnNlY3JldGtleWZvcnByb2plY3RtYW5hZ2VtZW50cGxhdGZvcm0=

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info